language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4.0"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - npm install -g npm
  - npm --version
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.8"
